#!/usr/bin/env python3
"""Package the rad_ai360_visualizer plugin as an installable .rbz file.

Run from anywhere:
    python build_rbz.py [--out <destination_dir>]

.rbz is just a ZIP whose root contains the loader stub and the plugin folder.
SketchUp installs it to the user Plugins directory automatically.
"""
import argparse, zipfile, sys
from pathlib import Path

PLUGIN_DIR  = Path(__file__).parent
PLUGIN_NAME = "rad_ai360_visualizer"
LOADER_STUB = f"{PLUGIN_NAME}.rb"

INCLUDE_EXTENSIONS = {".rb", ".py", ".json", ".md", ".txt"}
EXCLUDE_NAMES = {
    "__pycache__", ".git", "build_rbz.py", "build_exe.py",
    "config.json",          # excluded — user fills this in manually
    "config.example.json",  # added explicitly below to avoid rglob duplicate
    "ai360_pipeline.spec",
}
EXCLUDE_DIRS = {"build", "dist", "__pycache__"}
EXCLUDE_SUFFIXES = {".pyc", ".pyo", ".rbz"}


def should_include(path: Path) -> bool:
    for part in path.parts:
        if part in EXCLUDE_NAMES or part in EXCLUDE_DIRS:
            return False
    if path.suffix in EXCLUDE_SUFFIXES:
        return False
    if path.name in EXCLUDE_NAMES:
        return False
    return path.suffix in INCLUDE_EXTENSIONS


def build_rbz(out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    rbz_path = out_dir / f"{PLUGIN_NAME}.rbz"

    loader_content = f"""\
# RAD AI360 Visualizer — loader stub (auto-generated by build_rbz.py)
require File.join(File.dirname(__FILE__), '{PLUGIN_NAME}', 'main.rb')
"""

    with zipfile.ZipFile(rbz_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        # Loader stub at zip root
        zf.writestr(LOADER_STUB, loader_content)

        # Plugin files under rad_ai360_visualizer/
        for src in sorted(PLUGIN_DIR.rglob("*")):
            if not src.is_file():
                continue
            if not should_include(src):
                continue
            arc_name = PLUGIN_NAME + "/" + src.relative_to(PLUGIN_DIR).as_posix()
            zf.write(src, arc_name)
            print(f"  + {arc_name}")

        # config.example.json → include so user knows what to fill in
        example = PLUGIN_DIR / "config.example.json"
        if example.exists():
            zf.write(example, f"{PLUGIN_NAME}/config.example.json")
            print(f"  + {PLUGIN_NAME}/config.example.json")

    print(f"\nBuilt: {rbz_path}  ({rbz_path.stat().st_size // 1024} KB)")
    return rbz_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=Path(__file__).parent.parent)
    args = parser.parse_args()
    build_rbz(args.out)
